import type { AcceptedAnswer, CityCountryQuestion } from '@/types/practice';

// ─── City → Country question bank ─────────────────────────────────────────────
// Player types the country name; matching is forgiving (see cityCountryEngine's
// checkAnswer) against `answer` plus any `aliases` - common abbreviations or
// alternate names.
//
// difficulty 1: iconic capitals/cities
// difficulty 2: well-known but non-obvious cities (not always the capital)
// difficulty 3: lesser-known capitals - easy to confuse with neighboring countries

function cityAnswers(input: {
  broad: readonly string[];
  preferred?: readonly string[];
}): AcceptedAnswer[] {
  return [
    ...input.broad.map((value) => ({ value, specificity: 'broad' }) as const),
    ...(input.preferred ?? []).map((value) => ({ value, specificity: 'preferred' }) as const),
  ];
}

export const CITY_COUNTRY_QUESTIONS: CityCountryQuestion[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  { id: 'cc-e-001', type: 'city_country', city: 'Paris', continent: 'Europe',
    prompt: 'Which country is Paris in?', answer: 'France', aliases: [],
    explanation: 'Paris has been the capital of France since the late 10th century.', difficulty: 1 },
  { id: 'cc-e-002', type: 'city_country', city: 'Tokyo', continent: 'Asia',
    prompt: 'Which country is Tokyo in?', answer: 'Japan', aliases: [],
    explanation: 'Tokyo became the seat of Japan’s government in 1868, replacing Kyoto.', difficulty: 1 },
  { id: 'cc-e-003', type: 'city_country', city: 'Cairo', continent: 'Africa',
    prompt: 'Which country is Cairo in?', answer: 'Egypt', aliases: [],
    explanation: 'Cairo sits on the Nile and is the largest city in the Arab world.', difficulty: 1 },
  { id: 'cc-e-004', type: 'city_country', city: 'London', continent: 'Europe',
    prompt: 'Which country is London in?', answer: 'United Kingdom', aliases: ['UK', 'Britain', 'Great Britain', 'England'],
    explanation: 'London has been a major settlement for two millennia, founded as Londinium by the Romans.', difficulty: 1 },
  { id: 'cc-e-005', type: 'city_country', city: 'Rome', continent: 'Europe',
    prompt: 'Which country is Rome in?', answer: 'Italy', aliases: [],
    explanation: 'Rome is home to Vatican City, an independent state entirely within the city.', difficulty: 1 },
  { id: 'cc-e-006', type: 'city_country', city: 'Beijing', continent: 'Asia',
    prompt: 'Which country is Beijing in?', answer: 'China', aliases: [],
    explanation: 'Beijing means "northern capital" in Mandarin.', difficulty: 1 },
  { id: 'cc-e-007', type: 'city_country', city: 'Moscow', continent: 'Europe',
    prompt: 'Which country is Moscow in?', answer: 'Russia', aliases: [],
    explanation: 'Moscow is the largest city in Europe by population.', difficulty: 1 },
  { id: 'cc-e-008', type: 'city_country', city: 'Berlin', continent: 'Europe',
    prompt: 'Which country is Berlin in?', answer: 'Germany', aliases: [],
    explanation: 'Berlin was divided by a wall from 1961 to 1989.', difficulty: 1 },
  { id: 'cc-e-009', type: 'city_country', city: 'Madrid', continent: 'Europe',
    prompt: 'Which country is Madrid in?', answer: 'Spain', aliases: [],
    explanation: 'Madrid is the highest-altitude capital in the European Union.', difficulty: 1 },
  { id: 'cc-e-010', type: 'city_country', city: 'Sydney', continent: 'Oceania',
    prompt: 'Which country is Sydney in?', answer: 'Australia', aliases: [],
    explanation: 'Sydney is Australia’s largest city, though Canberra is the capital.', difficulty: 1 },
  { id: 'cc-e-011', type: 'city_country', city: 'Toronto', continent: 'North America',
    prompt: 'Which country is Toronto in?', answer: 'Canada', aliases: [],
    explanation: 'Toronto is Canada’s most populous city, though Ottawa is the capital.', difficulty: 1 },
  { id: 'cc-e-012', type: 'city_country', city: 'Rio de Janeiro', continent: 'South America',
    prompt: 'Which country is Rio de Janeiro in?', answer: 'Brazil', aliases: [],
    explanation: 'Rio was Brazil’s capital until Brasília took over in 1960.', difficulty: 1 },
  { id: 'cc-e-013', type: 'city_country', city: 'Mumbai', continent: 'Asia',
    prompt: 'Which country is Mumbai in?', answer: 'India', aliases: [],
    explanation: 'Mumbai, formerly Bombay, is India’s financial capital.', difficulty: 1 },
  { id: 'cc-e-014', type: 'city_country', city: 'Bangkok', continent: 'Asia',
    prompt: 'Which country is Bangkok in?', answer: 'Thailand', aliases: [],
    explanation: 'Bangkok’s full ceremonial name is one of the longest place names in the world.', difficulty: 1 },
  { id: 'cc-e-015', type: 'city_country', city: 'Athens', continent: 'Europe',
    prompt: 'Which country is Athens in?', answer: 'Greece', aliases: [],
    explanation: 'Athens is one of the oldest continuously inhabited cities in the world.', difficulty: 1 },
  { id: 'cc-e-016', type: 'city_country', city: 'Dubai', continent: 'Asia',
    prompt: 'Which country is Dubai in?', answer: 'United Arab Emirates', aliases: ['UAE', 'Emirates'],
    explanation: 'Dubai is the most populous of the UAE’s seven emirates, though Abu Dhabi is the capital.', difficulty: 1 },
  { id: 'cc-e-017', type: 'city_country', city: 'Amsterdam', continent: 'Europe',
    prompt: 'Which country is Amsterdam in?', answer: 'Netherlands', aliases: ['Holland'],
    explanation: 'Amsterdam is the constitutional capital, though the government sits in The Hague.', difficulty: 1 },
  { id: 'cc-e-018', type: 'city_country', city: 'Istanbul', continent: 'Europe',
    prompt: 'Which country is Istanbul in?', answer: 'Turkey', aliases: ['Turkiye', 'Türkiye'],
    explanation: 'Istanbul straddles both Europe and Asia across the Bosphorus.', difficulty: 1 },
  { id: 'cc-e-019', type: 'city_country', city: 'Mexico City', continent: 'North America',
    prompt: 'Which country is Mexico City in?', answer: 'Mexico', aliases: [],
    explanation: 'Mexico City was built atop the Aztec capital of Tenochtitlan.', difficulty: 1 },
  { id: 'cc-e-020', type: 'city_country', city: 'Vienna', continent: 'Europe',
    prompt: 'Which country is Vienna in?', answer: 'Austria', aliases: [],
    explanation: 'Vienna was long the seat of the Habsburg dynasty.', difficulty: 1 },
  { id: 'cc-e-021', type: 'city_country', city: 'Stratford-upon-Avon', continent: 'Europe',
    prompt: 'Which country is Stratford-upon-Avon in?', answer: 'UK', aliases: ['United Kingdom', 'England'],
    explanation: 'Stratford-upon-Avon draws visitors worldwide as the birthplace of William Shakespeare.', difficulty: 1 },
  { id: 'cc-e-022', type: 'city_country', city: 'Shanghai', continent: 'Asia',
    prompt: 'Which country is Shanghai in?', answer: 'China', aliases: [],
    explanation: 'Shanghai is China’s largest city and one of the world’s busiest container ports.', difficulty: 1 },
  { id: 'cc-e-023', type: 'city_country', city: 'Tehran', continent: 'Asia',
    prompt: 'Which country is Tehran in?', answer: 'Iran', aliases: [],
    explanation: 'Tehran has been Iran’s capital since 1795 and sits at the foot of the Alborz mountains.', difficulty: 1 },
  { id: 'cc-e-024', type: 'city_country', city: 'Kyiv', continent: 'Europe',
    prompt: 'Which country is Kyiv in?', answer: 'Ukraine', aliases: ['Kiev'],
    explanation: 'Kyiv is one of the oldest cities in Eastern Europe, tracing its founding to the 5th century.', difficulty: 1 },

  // ── Medium ────────────────────────────────────────────────────────────────
  { id: 'cc-m-001', type: 'city_country', city: 'Barcelona', continent: 'Europe',
    prompt: 'Which country is Barcelona in?', answer: 'Spain', aliases: ['Catalonia', 'Catalunya'],
    acceptedAnswers: cityAnswers({ broad: ['Spain', 'Spanish'], preferred: ['Catalonia', 'Catalunya'] }),
    explanation: 'Barcelona is the capital of the autonomous region of Catalonia.', difficulty: 2 },
  { id: 'cc-m-002', type: 'city_country', city: 'Munich', continent: 'Europe',
    prompt: 'Which country is Munich in?', answer: 'Germany', aliases: [],
    explanation: 'Munich is the capital of Bavaria and home of Oktoberfest.', difficulty: 2 },
  { id: 'cc-m-003', type: 'city_country', city: 'Osaka', continent: 'Asia',
    prompt: 'Which country is Osaka in?', answer: 'Japan', aliases: [],
    explanation: 'Osaka was historically Japan’s merchant capital.', difficulty: 2 },
  { id: 'cc-m-004', type: 'city_country', city: 'Marrakesh', continent: 'Africa',
    prompt: 'Which country is Marrakesh in?', answer: 'Morocco', aliases: [],
    explanation: 'Marrakesh gave Morocco its name in several European languages.', difficulty: 2 },
  { id: 'cc-m-005', type: 'city_country', city: 'Cape Town', continent: 'Africa',
    prompt: 'Which country is Cape Town in?', answer: 'South Africa', aliases: [],
    explanation: 'Cape Town is South Africa’s legislative capital.', difficulty: 2 },
  { id: 'cc-m-006', type: 'city_country', city: 'Auckland', continent: 'Oceania',
    prompt: 'Which country is Auckland in?', answer: 'New Zealand', aliases: ['NZ'],
    explanation: 'Auckland is New Zealand’s largest city, though Wellington is the capital.', difficulty: 2 },
  { id: 'cc-m-007', type: 'city_country', city: 'Kyoto', continent: 'Asia',
    prompt: 'Which country is Kyoto in?', answer: 'Japan', aliases: [],
    explanation: 'Kyoto served as Japan’s capital for over a thousand years.', difficulty: 2 },
  { id: 'cc-m-008', type: 'city_country', city: 'Zurich', continent: 'Europe',
    prompt: 'Which country is Zurich in?', answer: 'Switzerland', aliases: [],
    explanation: 'Zurich is Switzerland’s largest city, though Bern is the capital.', difficulty: 2 },
  { id: 'cc-m-009', type: 'city_country', city: 'Porto', continent: 'Europe',
    prompt: 'Which country is Porto in?', answer: 'Portugal', aliases: [],
    explanation: 'Port wine takes its name from this city.', difficulty: 2 },
  { id: 'cc-m-010', type: 'city_country', city: 'Krakow', continent: 'Europe',
    prompt: 'Which country is Krakow in?', answer: 'Poland', aliases: [],
    explanation: 'Krakow was Poland’s capital until 1596.', difficulty: 2 },
  { id: 'cc-m-011', type: 'city_country', city: 'Busan', continent: 'Asia',
    prompt: 'Which country is Busan in?', answer: 'South Korea', aliases: ['Korea', 'Republic of Korea'],
    explanation: 'Busan is South Korea’s largest port city.', difficulty: 2 },
  { id: 'cc-m-012', type: 'city_country', city: 'Casablanca', continent: 'Africa',
    prompt: 'Which country is Casablanca in?', answer: 'Morocco', aliases: [],
    explanation: 'Casablanca is Morocco’s largest city and economic hub.', difficulty: 2 },
  { id: 'cc-m-013', type: 'city_country', city: 'Medellín', continent: 'South America',
    prompt: 'Which country is Medellín in?', answer: 'Colombia', aliases: [],
    explanation: 'Medellín is known as the "City of Eternal Spring" for its climate.', difficulty: 2 },
  { id: 'cc-m-014', type: 'city_country', city: 'Nairobi', continent: 'Africa',
    prompt: 'Which country is Nairobi in?', answer: 'Kenya', aliases: [],
    explanation: 'Nairobi is the only capital city in the world with a national park within it.', difficulty: 2 },
  { id: 'cc-m-015', type: 'city_country', city: 'Reykjavik', continent: 'Europe',
    prompt: 'Which country is Reykjavik in?', answer: 'Iceland', aliases: [],
    explanation: 'Reykjavik is the world’s northernmost capital of a sovereign state.', difficulty: 2 },
  { id: 'cc-m-016', type: 'city_country', city: 'Wellington', continent: 'Oceania',
    prompt: 'Which country is Wellington in?', answer: 'New Zealand', aliases: ['NZ'],
    explanation: 'Wellington is the world’s southernmost capital city.', difficulty: 2 },
  { id: 'cc-m-017', type: 'city_country', city: 'Tbilisi', continent: 'Asia',
    prompt: 'Which country is Tbilisi in?', answer: 'Georgia', aliases: [],
    explanation: 'Tbilisi straddles the boundary often drawn between Europe and Asia.', difficulty: 2 },
  { id: 'cc-m-018', type: 'city_country', city: 'Hanoi', continent: 'Asia',
    prompt: 'Which country is Hanoi in?', answer: 'Vietnam', aliases: [],
    explanation: 'Hanoi has served as Vietnam’s capital for over a thousand years, on and off.', difficulty: 2 },
  { id: 'cc-m-019', type: 'city_country', city: 'Yerevan', continent: 'Asia',
    prompt: 'Which country is Yerevan in?', answer: 'Armenia', aliases: [],
    explanation: 'Yerevan is one of the oldest continuously inhabited cities in the world.', difficulty: 2 },
  { id: 'cc-m-020', type: 'city_country', city: 'Quito', continent: 'South America',
    prompt: 'Which country is Quito in?', answer: 'Ecuador', aliases: [],
    explanation: 'Quito sits almost exactly on the equator, giving Ecuador its name.', difficulty: 2 },
  { id: 'cc-m-022', type: 'city_country', city: 'Dhaka', continent: 'Asia',
    prompt: 'Which country is Dhaka in?', answer: 'Bangladesh', aliases: [],
    explanation: 'Dhaka is one of the most densely populated cities on Earth and is nicknamed the "City of Mosques."', difficulty: 2 },
  { id: 'cc-m-023', type: 'city_country', city: 'Lahore', continent: 'Asia',
    prompt: 'Which country is Lahore in?', answer: 'Pakistan', aliases: [],
    explanation: 'Lahore is Pakistan’s cultural capital, home to the Mughal-era Badshahi Mosque.', difficulty: 2 },
  { id: 'cc-m-024', type: 'city_country', city: 'Montego Bay', continent: 'North America',
    prompt: 'Which country is Montego Bay in?', answer: 'Jamaica', aliases: [],
    explanation: 'Montego Bay is one of Jamaica’s largest cities and a major cruise-ship port on its north coast.', difficulty: 2 },
  { id: 'cc-m-025', type: 'city_country', city: 'Uppsala', continent: 'Europe',
    prompt: 'Which country is Uppsala in?', answer: 'Sweden', aliases: [],
    explanation: 'Uppsala is home to Uppsala University, founded in 1477 and the oldest in Scandinavia.', difficulty: 2 },
  { id: 'cc-m-026', type: 'city_country', city: 'Chittagong', continent: 'Asia',
    prompt: 'Which country is Chittagong in?', answer: 'Bangladesh', aliases: [],
    explanation: 'Chittagong is Bangladesh’s principal seaport and its second-largest city.', difficulty: 2 },
  { id: 'cc-m-027', type: 'city_country', city: "Xi'an", continent: 'Asia',
    prompt: "Which country is Xi'an in?", answer: 'China', aliases: ['Xian'],
    explanation: 'Xi’an marks the eastern starting point of the ancient Silk Road and is home to the Terracotta Army.', difficulty: 2 },
  { id: 'cc-m-028', type: 'city_country', city: 'Sapporo', continent: 'Asia',
    prompt: 'Which country is Sapporo in?', answer: 'Japan', aliases: [],
    explanation: 'Sapporo is the largest city on Japan’s northern island of Hokkaido, known for its winter snow festival.', difficulty: 2 },
  { id: 'cc-m-029', type: 'city_country', city: 'Nagasaki', continent: 'Asia',
    prompt: 'Which country is Nagasaki in?', answer: 'Japan', aliases: [],
    explanation: 'Nagasaki was one of the only Japanese ports open to foreign trade during centuries of national isolation.', difficulty: 2 },
  { id: 'cc-m-030', type: 'city_country', city: 'Doha', continent: 'Asia',
    prompt: 'Which country is Doha in?', answer: 'Qatar', aliases: [],
    explanation: 'Doha is Qatar’s capital and hosted the 2022 FIFA World Cup.', difficulty: 2 },
  { id: 'cc-m-031', type: 'city_country', city: 'Muscat', continent: 'Asia',
    prompt: 'Which country is Muscat in?', answer: 'Oman', aliases: [],
    explanation: 'Muscat is the capital of Oman, a sultanate on the southeastern Arabian Peninsula.', difficulty: 2 },
  { id: 'cc-m-032', type: 'city_country', city: 'Bengaluru', continent: 'Asia',
    prompt: 'Which country is Bengaluru in?', answer: 'India', aliases: ['Bangalore'],
    explanation: 'Bengaluru, formerly Bangalore, is often called the "Silicon Valley of India."', difficulty: 2 },
  { id: 'cc-m-033', type: 'city_country', city: 'Porto Alegre', continent: 'South America',
    prompt: 'Which country is Porto Alegre in?', answer: 'Brazil', aliases: [],
    explanation: 'Porto Alegre is the capital of Brazil’s southernmost state, Rio Grande do Sul.', difficulty: 2 },
  { id: 'cc-m-034', type: 'city_country', city: 'Recife', continent: 'South America',
    prompt: 'Which country is Recife in?', answer: 'Brazil', aliases: [],
    explanation: 'Recife’s network of rivers and bridges has earned it the nickname "Venice of Brazil."', difficulty: 2 },
  { id: 'cc-m-035', type: 'city_country', city: 'Samarkand', continent: 'Asia',
    prompt: 'Which country is Samarkand in?', answer: 'Uzbekistan', aliases: [],
    explanation: 'Samarkand was a major Silk Road hub and is famed for its Registan square.', difficulty: 2 },
  { id: 'cc-m-036', type: 'city_country', city: 'Hyderabad', continent: 'Asia',
    prompt: 'Which country is Hyderabad in?', answer: 'India', aliases: ['Pakistan'],
    explanation: 'There are two major cities named Hyderabad - one in India’s Telangana state, another in Pakistan’s Sindh province - both are accepted here.', difficulty: 2 },
  { id: 'cc-m-037', type: 'city_country', city: 'Odesa', continent: 'Europe',
    prompt: 'Which country is Odesa in?', answer: 'Ukraine', aliases: ['Odessa'],
    explanation: 'Odesa is Ukraine’s largest Black Sea port, known for its 19th-century Potemkin Stairs.', difficulty: 2 },
  { id: 'cc-m-038', type: 'city_country', city: 'Pretoria', continent: 'Africa',
    prompt: 'Which country is Pretoria in?', answer: 'South Africa', aliases: [],
    explanation: 'Pretoria is South Africa’s administrative capital, while Cape Town and Bloemfontein handle the legislative and judicial branches.', difficulty: 2 },
  { id: 'cc-m-039', type: 'city_country', city: 'Kigali', continent: 'Africa',
    prompt: 'Which country is Kigali in?', answer: 'Rwanda', aliases: [],
    explanation: 'Kigali is widely regarded as one of Africa’s cleanest and safest capital cities.', difficulty: 2 },
  { id: 'cc-m-040', type: 'city_country', city: 'Port-au-Prince', continent: 'North America',
    prompt: 'Which country is Port-au-Prince in?', answer: 'Haiti', aliases: [],
    explanation: 'Port-au-Prince is Haiti’s capital and largest city, founded by French colonists in 1749.', difficulty: 2 },
  { id: 'cc-m-041', type: 'city_country', city: 'Chiang Mai', continent: 'Asia',
    prompt: 'Which country is Chiang Mai in?', answer: 'Thailand', aliases: [],
    explanation: 'Chiang Mai was the capital of the independent Lanna Kingdom before becoming part of Thailand.', difficulty: 2 },

  // ── Hard ──────────────────────────────────────────────────────────────────
  { id: 'cc-h-001', type: 'city_country', city: 'Ouagadougou', continent: 'Africa',
    prompt: 'Which country is Ouagadougou in?', answer: 'Burkina Faso', aliases: [],
    explanation: 'Ouagadougou is the capital and largest city of Burkina Faso.', difficulty: 3 },
  { id: 'cc-h-002', type: 'city_country', city: 'Bishkek', continent: 'Asia',
    prompt: 'Which country is Bishkek in?', answer: 'Kyrgyzstan', aliases: [],
    explanation: 'Bishkek was known as Frunze during the Soviet era.', difficulty: 3 },
  { id: 'cc-h-003', type: 'city_country', city: 'Ljubljana', continent: 'Europe',
    prompt: 'Which country is Ljubljana in?', answer: 'Slovenia', aliases: [],
    explanation: 'Ljubljana is Slovenia’s capital and largest city.', difficulty: 3 },
  { id: 'cc-h-004', type: 'city_country', city: 'Vaduz', continent: 'Europe',
    prompt: 'Which country is Vaduz in?', answer: 'Liechtenstein', aliases: [],
    explanation: 'Vaduz is the capital of Liechtenstein, one of the world’s smallest countries.', difficulty: 3 },
  { id: 'cc-h-005', type: 'city_country', city: 'Antananarivo', continent: 'Africa',
    prompt: 'Which country is Antananarivo in?', answer: 'Madagascar', aliases: [],
    explanation: 'Antananarivo is often shortened to "Tana" by locals.', difficulty: 3 },
  { id: 'cc-h-006', type: 'city_country', city: 'Ulaanbaatar', continent: 'Asia',
    prompt: 'Which country is Ulaanbaatar in?', answer: 'Mongolia', aliases: [],
    explanation: 'Ulaanbaatar is the coldest capital city in the world.', difficulty: 3 },
  { id: 'cc-h-007', type: 'city_country', city: 'Asunción', continent: 'South America',
    prompt: 'Which country is Asunción in?', answer: 'Paraguay', aliases: [],
    explanation: 'Asunción is one of the oldest cities in South America, founded in 1537.', difficulty: 3 },
  { id: 'cc-h-008', type: 'city_country', city: 'Bratislava', continent: 'Europe',
    prompt: 'Which country is Bratislava in?', answer: 'Slovakia', aliases: [],
    explanation: 'Bratislava is the only national capital bordering two other countries.', difficulty: 3 },
  { id: 'cc-h-009', type: 'city_country', city: 'Vilnius', continent: 'Europe',
    prompt: 'Which country is Vilnius in?', answer: 'Lithuania', aliases: [],
    explanation: 'Vilnius has one of the largest surviving medieval old towns in Europe.', difficulty: 3 },
  { id: 'cc-h-010', type: 'city_country', city: 'Chișinău', continent: 'Europe',
    prompt: 'Which country is Chișinău in?', answer: 'Moldova', aliases: [],
    explanation: 'Chișinău is Moldova’s capital and its largest wine-trading hub.', difficulty: 3 },
  { id: 'cc-h-011', type: 'city_country', city: 'Podgorica', continent: 'Europe',
    prompt: 'Which country is Podgorica in?', answer: 'Montenegro', aliases: [],
    explanation: 'Podgorica was called Titograd from 1946 to 1992.', difficulty: 3 },
  { id: 'cc-h-012', type: 'city_country', city: 'Nouakchott', continent: 'Africa',
    prompt: 'Which country is Nouakchott in?', answer: 'Mauritania', aliases: [],
    explanation: 'Nouakchott grew from a small village into a capital of over a million almost entirely after 1960.', difficulty: 3 },
  { id: 'cc-h-013', type: 'city_country', city: 'Bandar Seri Begawan', continent: 'Asia',
    prompt: 'Which country is Bandar Seri Begawan in?', answer: 'Brunei', aliases: [],
    explanation: 'Bandar Seri Begawan is the capital of the oil-rich sultanate of Brunei.', difficulty: 3 },
  { id: 'cc-h-014', type: 'city_country', city: 'Thimphu', continent: 'Asia',
    prompt: 'Which country is Thimphu in?', answer: 'Bhutan', aliases: [],
    explanation: 'Thimphu is one of the few capital cities without traffic lights.', difficulty: 3 },
  { id: 'cc-h-015', type: 'city_country', city: 'Dushanbe', continent: 'Asia',
    prompt: 'Which country is Dushanbe in?', answer: 'Tajikistan', aliases: [],
    explanation: 'Dushanbe means "Monday" in Persian, named for a Monday market once held there.', difficulty: 3 },
  { id: 'cc-h-016', type: 'city_country', city: "Nukuʻalofa", continent: 'Oceania',
    prompt: "Which country is Nukuʻalofa in?", answer: 'Tonga', aliases: [],
    explanation: "Nukuʻalofa is the capital of the Kingdom of Tonga, the only Pacific nation never colonized.", difficulty: 3 },
  { id: 'cc-h-017', type: 'city_country', city: 'Gaborone', continent: 'Africa',
    prompt: 'Which country is Gaborone in?', answer: 'Botswana', aliases: [],
    explanation: 'Gaborone was built specifically to be Botswana’s capital ahead of independence in 1966.', difficulty: 3 },
  { id: 'cc-h-018', type: 'city_country', city: 'Ashgabat', continent: 'Asia',
    prompt: 'Which country is Ashgabat in?', answer: 'Turkmenistan', aliases: [],
    explanation: 'Ashgabat holds a Guinness World Record for the highest density of white marble buildings.', difficulty: 3 },
  { id: 'cc-h-019', type: 'city_country', city: 'Tegucigalpa', continent: 'North America',
    prompt: 'Which country is Tegucigalpa in?', answer: 'Honduras', aliases: [],
    explanation: 'Tegucigalpa’s name likely comes from an indigenous Nahuatl phrase meaning "silver hill."', difficulty: 3 },
  { id: 'cc-h-020', type: 'city_country', city: 'Bujumbura', continent: 'Africa',
    prompt: 'Which country is Bujumbura in?', answer: 'Burundi', aliases: [],
    explanation: 'Bujumbura sits on the shore of Lake Tanganyika and was Burundi’s capital until 2019.', difficulty: 3 },
  { id: 'cc-h-021', type: 'city_country', city: 'Bridgetown', continent: 'North America',
    prompt: 'Which country is Bridgetown in?', answer: 'Barbados', aliases: [],
    explanation: 'Bridgetown’s historic garrison was named a UNESCO World Heritage Site in 2011.', difficulty: 3 },
  { id: 'cc-h-022', type: 'city_country', city: 'Rangpur', continent: 'Asia',
    prompt: 'Which country is Rangpur in?', answer: 'Bangladesh', aliases: [],
    explanation: 'Rangpur is a major city in northern Bangladesh known for its tobacco and rice trade.', difficulty: 3 },
  { id: 'cc-h-023', type: 'city_country', city: 'Quetta', continent: 'Asia',
    prompt: 'Which country is Quetta in?', answer: 'Pakistan', aliases: [],
    explanation: 'Quetta is the capital of Pakistan’s Balochistan province, ringed by mountains.', difficulty: 3 },
  { id: 'cc-h-024', type: 'city_country', city: 'Kashgar', continent: 'Asia',
    prompt: 'Which country is Kashgar in?', answer: 'China', aliases: ['Kashi'],
    explanation: 'Kashgar was a key Silk Road oasis city in China’s far-western Xinjiang region.', difficulty: 3 },
  { id: 'cc-h-025', type: 'city_country', city: 'Ürümqi', continent: 'Asia',
    prompt: 'Which country is Ürümqi in?', answer: 'China', aliases: ['Urumqi'],
    explanation: 'Ürümqi, capital of Xinjiang, is often cited as the city farthest from any ocean on Earth.', difficulty: 3 },
  { id: 'cc-h-026', type: 'city_country', city: 'Vellore', continent: 'Asia',
    prompt: 'Which country is Vellore in?', answer: 'India', aliases: [],
    explanation: 'Vellore is known for its 16th-century fort and a major medical college that draws patients nationwide.', difficulty: 3 },
  { id: 'cc-h-027', type: 'city_country', city: 'Faridabad', continent: 'Asia',
    prompt: 'Which country is Faridabad in?', answer: 'India', aliases: [],
    explanation: 'Faridabad is a satellite city of Delhi and one of the most populous cities in the state of Haryana.', difficulty: 3 },
  { id: 'cc-h-028', type: 'city_country', city: 'Faisalabad', continent: 'Asia',
    prompt: 'Which country is Faisalabad in?', answer: 'Pakistan', aliases: [],
    explanation: 'Faisalabad is Pakistan’s third-largest city and a major hub of textile manufacturing.', difficulty: 3 },
  { id: 'cc-h-029', type: 'city_country', city: 'Bandar Abbas', continent: 'Asia',
    prompt: 'Which country is Bandar Abbas in?', answer: 'Iran', aliases: [],
    explanation: 'Bandar Abbas is Iran’s main port on the strategically vital Strait of Hormuz.', difficulty: 3 },
  { id: 'cc-h-030', type: 'city_country', city: 'Sri Jayawardenepura Kotte', continent: 'Asia',
    prompt: 'Which country is Sri Jayawardenepura Kotte in?', answer: 'Sri Lanka', aliases: ['Kotte', 'Sri Jayawardenapura'],
    explanation: 'Sri Jayawardenepura Kotte is Sri Lanka’s official administrative capital, even though nearby Colombo is larger and better known.', difficulty: 3 },
  { id: 'cc-h-031', type: 'city_country', city: 'Kandahar', continent: 'Asia',
    prompt: 'Which country is Kandahar in?', answer: 'Afghanistan', aliases: [],
    explanation: 'Kandahar is Afghanistan’s second-largest city and a historic center of Pashtun culture.', difficulty: 3 },
  { id: 'cc-h-032', type: 'city_country', city: 'Murmansk', continent: 'Europe',
    prompt: 'Which country is Murmansk in?', answer: 'Russia', aliases: [],
    explanation: 'Murmansk is the largest city in the world located north of the Arctic Circle.', difficulty: 3 },
  { id: 'cc-h-033', type: 'city_country', city: 'Windhoek', continent: 'Africa',
    prompt: 'Which country is Windhoek in?', answer: 'Namibia', aliases: [],
    explanation: 'Windhoek is Namibia’s capital, sitting on a plateau roughly at the country’s center.', difficulty: 3 },
  { id: 'cc-h-034', type: 'city_country', city: 'Nizhny Novgorod', continent: 'Europe',
    prompt: 'Which country is Nizhny Novgorod in?', answer: 'Russia', aliases: ['Nizhniy Novgorod'],
    explanation: 'Nizhny Novgorod sits at the confluence of the Volga and Oka rivers and was closed to foreigners for decades during the Soviet era.', difficulty: 3 },
  { id: 'cc-h-035', type: 'city_country', city: 'Nuwara Eliya', continent: 'Asia',
    prompt: 'Which country is Nuwara Eliya in?', answer: 'Sri Lanka', aliases: ['Sri Lankan'],
    explanation: 'Nuwara Eliya is a hill-country city in Sri Lanka known for tea estates and cool highland weather.', difficulty: 3 },
  { id: 'cc-h-036', type: 'city_country', city: 'Jaffna', continent: 'Asia',
    prompt: 'Which country is Jaffna in?', answer: 'Sri Lanka', aliases: ['Sri Lankan'],
    explanation: 'Jaffna is a major city in northern Sri Lanka and a historic center of Sri Lankan Tamil culture.', difficulty: 3 },
  { id: 'cc-h-037', type: 'city_country', city: 'Rajamahendravaram', continent: 'Asia',
    prompt: 'Which country is Rajamahendravaram in?', answer: 'India', aliases: ['Andhra Pradesh', 'Andhra'],
    acceptedAnswers: cityAnswers({ broad: ['India', 'Indian'], preferred: ['Andhra Pradesh', 'Andhra'] }),
    explanation: 'Rajamahendravaram, also called Rajahmundry, is a city in Andhra Pradesh, India.', difficulty: 3 },
  { id: 'cc-h-038', type: 'city_country', city: 'Ballari', continent: 'Asia',
    prompt: 'Which country is Ballari in?', answer: 'India', aliases: ['Karnataka', 'Bellary'],
    acceptedAnswers: cityAnswers({ broad: ['India', 'Indian'], preferred: ['Karnataka'] }),
    explanation: 'Ballari, also known as Bellary, is a city in Karnataka, India.', difficulty: 3 },
];
